detaylandirma
androCyber/yemekhane_otomasyon pull request #3
Opened 2022-07-13 03:48 UTC by asaita

pull request işlemi

2022-07-13 17:31 UTC, androCyber requested changes

2022-07-15 09:36 UTC, asaita commented on README.md
> +Readme Dosyasının Detaylandırılıp oluşturulması gerekmektedir dedin yaptık agaaaaaa
tamam ekledim

2022-07-17 03:00 UTC, asaita commented on README.md
> +Readme Dosyasının Detaylandırılıp oluşturulması gerekmektedir dedin yaptık agaaaaaa
tekrar ekledim

2022-07-17 03:19 UTC, androCyber approved these changes

2022-07-17 03:25 UTC, merged